---
- hosts: all
  remote_user: root 
  gather_facts: False

  vars:
    port: 7474/tcp
    state: enabled  # enabled: open, disabled: close

  tasks:
    - name: check if firewalld is running
      command: systemctl is-active firewalld
      register: firewalld_result
      changed_when: False
      ignore_errors: True  # rc is 3 when firewalld is stopped

    - name: set the port state
      firewalld: permanent=true port={{ port }} state={{ state }}
#      notify: reload firewalld
#      when: firewalld_result.stdout == "active"

#  handlers:
#    - name: reload firewalld
#      service: name=firewalld state=restarted
